### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by JosiahRegencia**
For issue #25

### CODE REVIEW

**Comment by JosiahRegencia** [comment]
Not sure why it shows failed in here. It clearly shows that it passed in travis:
https://travis-ci.org/Doveps/mono/builds

**Comment by greenmoss** [comment]
Hi @JosiahRegencia the code climate thing is something I added. You can ignore it. I think I should remove it so we don't get an ugly red "X".

**Comment by greenmoss** [comment]
I think the scanner results need to be set aside somewhere, as they are for test purposes only. If you leave them directly in the `local` directory, they will also be created when someone new checks out the code. That would give the new person a set of scan results that they didn't create.

**Comment by greenmoss** [comment]
Need to fix the conflicting `.travis.yml`

**Comment by greenmoss** [comment]
Please reduce the amount of lines in the `33.33.33.5*` files. You only need a few lines in there: "just enough to get the test to pass". Otherwise it adds a lot of un-needed size in the repository.

**Comment by greenmoss** [comment]
The db stuff looks like it took a while, so I moved it into #28.

**Comment by JosiahRegencia** [comment]
@greenmoss But I need the scanner results in the repository so that travis can be able to read them.

**Pull request merged**
