### PR TITLE
Fixed hard-coded directories

### PR DESCRIPTION
**Pull request by JosiahRegencia**
For issue #29 

It fails in travis because I checked this one from master. So travis was not updated in master yet.

### CODE REVIEW

**Comment by JosiahRegencia** [comment]
Although in fix_tests branch, I also already fixed the hard-coded directories

**Comment by greenmoss** [comment]
Merge from your testing branch into this one, then see if it works

**Comment by JosiahRegencia** [comment]
My testing branch is already deleted

**Comment by greenmoss** [comment]
Yeah I merged testing into master; you can merge master into this one.

**Comment by greenmoss** [comment]
Replaced by #35

**Pull request closed without merging**
