### PR TITLE
Test code

### PR DESCRIPTION
**Pull request by JosiahRegencia**
This is for issue #30 Merged this with hard_coded branch and also master.

### CODE REVIEW

**Comment by greenmoss** [comment]
Can you merge this branch fixes into #30? Or does this replace #30?

**Comment by JosiahRegencia** [comment]
It replaces #30

**Comment by greenmoss** [comment]
Fixes #29

**Comment by JosiahRegencia** [comment]
Yeah. That's what it is.

**Comment by greenmoss** [comment]
The path hard-codings are gone, so 👍 

Still need to read the DB settings from a non-git config file: savant/app/run_sql.py#L7

(EDIT: was "get rid of")

**Comment by greenmoss** [comment]
Also please ensure you are always using 4 spaces for indent.

See
- savant/app/comparison.py
- savant/app/base_path.py

etc

You can update your editor to set that configuration.

**Comment by JosiahRegencia** [comment]
Still need to read the DB settings from a non-git config file: savant/app/run_sql.py#L7

I don't get this part

**Comment by JosiahRegencia** [comment]
My tab_size has already been set to 4 spaces by default.

**Comment by greenmoss** [comment]
There are still a bunch of `*.py` files with tabs:

```
$ find . -name '*.py' | xargs grep -rl '\t'
./app/base_path.py
./app/check_exists.py
./app/comparison.py
./app/get_scanned.py
./app/record.py
./app/results.py
./app/run_sql.py
./app/store_data.py
./tests/test_basic.py
```

I checked the Travis tests, the mixed spaces/tabs is causing the test failure.

**Comment by JosiahRegencia** [comment]
Ran the command you gave me on vim. Although, find . -name '*.py' | xargs grep -rl '\t' still outputs the files. But I can see the difference in indents in the commits, though

**Comment by greenmoss** [comment]
There are a few remaining tabs:

https://github.com/Doveps/mono/pull/35/files#diff-e86e3a52272382f82b6b21af21658398R10

line 10-15

**Pull request merged**
