### PR TITLE
Saveas null

### PR DESCRIPTION
**Pull request by JosiahRegencia**
Fixed the null issue in this one

### CODE REVIEW

**Comment by greenmoss** [comment]
It is better to base each change from dev. As is, we need to wait for #71 to merge before I can merge this.

**Comment by greenmoss** [comment]
This is for #69 right?

Can you add a test case for the null values?

**Comment by JosiahRegencia** [comment]
I'll checkout master again and then make the changes. 

Will the test cases be on the same ticket or on a different ticket?

**Comment by JosiahRegencia** [comment]
Sorry. I forgot to mention. But this PR should be deleted.

**Pull request closed without merging**
