### PR TITLE
Issue32

### PR DESCRIPTION
**Pull request by JosiahRegencia**
This is already for both issue #32 and #33

### CODE REVIEW

**Comment by greenmoss** [comment]
Needs merge from master and resolve conflicts

**Comment by JosiahRegencia** [comment]
Okay. But, I'm still actually confused about the merging stuff. What I think of is:
1. Checkout my_branch
2. git pull origin master.

Is that correct?

**Comment by greenmoss** [comment]
yeah, that's about right

```
git fetch -ap
git checkout issue32
git pull origin master
```

**Comment by JosiahRegencia** [comment]
right will do

**Comment by JosiahRegencia** [comment]
I'm just going to be pushing it in master right?

**Comment by greenmoss** [comment]
* push to your branch `issue32` first
* ensure tests pass
* then I can approve the PR, which merges to master

**Comment by JosiahRegencia** [comment]
Right. I forgot which branch I was. But about the tests passing, I'm still looking for a solution that allows me to upload file in unittests

**Comment by JosiahRegencia** [comment]
Finally got it to pass in travis. But I don't really understand codeclimate yet

**Pull request merged**
