### PR TITLE
Added unit tests

### PR DESCRIPTION
**Pull request by JosiahRegencia**
I made this unit tests after I fixed the Duplicates in the DB. So I figured to make the DB_Duplicate_Tables the base. This is for issue #19 Though I'm still going to make travis work. Still studying it a bit

### CODE REVIEW

**Comment by zerstoeren** [comment]
I will try to review the.unit tests as well.  Just want to document here that Josiah and I are trying to find a schedule time to meet on Travis, but I am blocking his progress in the Travis integration due to treatment weekend.  We will find some time next week to meet once I have recovered from the weekend.

**Comment by zerstoeren** [comment]
Kurt... can you review as well.  I am having double vision right now.

**Comment by greenmoss** [comment]
@zerstoeren yeah checking it out now

**Comment by greenmoss** [comment]
The test looks good. The last part is to figure out how to hook us up to Travis, and have it automatically execute this test.

**Comment by JosiahRegencia** [comment]
Yup. Initially Randy and I agreed to meet on Monday for Travis

**Comment by greenmoss** [comment]
@JosiahRegencia I have a conflict for today, but I can meet with you tomorrow morning (Sunday evening your time). See how far you can get with Travis, and we'll talk then. Does that work for you?

**Comment by JosiahRegencia** [comment]
@greenmoss sure. that's good. I'll see what I can do.

**Comment by greenmoss** [comment]
Doing new branch, without the accidental file deletion

**Pull request closed without merging**
