### PR TITLE
Refactor query

### PR DESCRIPTION
**Pull request by JosiahRegencia**
Was able to remove set_engine_name() and was able to avoid calling it every time I call a function for a set of queries.

One drawback however is: psycopg2 cursor and connections don't close. Because if I close them, we can't be able to run other queries. Unless if we create new ones. Which somehow defeats the purpose of removing set_engine_name(). What happens is that when a query is run it continues to pile up the cache since only one cursor is used. I want to find a way to be able to close a cursor after a certain time it's not used or maybe only after a certain time and then create a new cursor with the same variables. haven't found anything really helpful yet, though.

### CODE REVIEW

**Comment by greenmoss** [comment]
Which issue is this linked to? Do you want me to merge it?

What do you think about the codeclimate issues?

**Comment by JosiahRegencia** [comment]
85

**Comment by greenmoss** [comment]
Linking to #85

**Comment by JosiahRegencia** [comment]
Hi Kurt (@greenmoss ),

Sorry I just checked codeclimate right now. Most of its issues were similar to the issues we previously had which you guys decided to make codeclimate ignore. The issues were that there are some functions that look the same because they seem to have the same structure. The thing is that each function calls a different function in postgres. But its structure is the same so codeclimate has issues with it. But as I said, in the previous this was ignored. I can try to find a way to minimize the repeat of the structure of those functions if you want me to.

**Comment by JosiahRegencia** [comment]
Like this one:

https://github.com/Doveps/mono/blob/dd024f1e7849049723699822fd7b2427d4b63afe/savant/app/query.py#L59-L71

**Comment by greenmoss** [comment]
Adding do not merge label, until @JosiahRegencia wants it merged

**Comment by zerstoeren** [comment]
Is there a benefit to storing the psycopg2 output into a dict to be able to
close the connection and open a new one or will that not work?  I did this
once, but the stored information was not anywhere near what this is doing.

**Comment by JosiahRegencia** [comment]
@zerstoeren the purpose of the json file where the result was stored was for when the new data will be added to knowledge tables.

**Comment by JosiahRegencia** [comment]
I'm not really sure what benefit you are referring to @zerstoeren

**Comment by JosiahRegencia** [comment]
@greenmoss can we have this one merged? And then I'll work on the concern of @zerstoeren on a separate ticket? I think I need the changes a I made from this branch. I plan on creating a new branch for the travis-docker stuff. But not have travis-docker deleted yet.

**Comment by greenmoss** [comment]
Ignoring codeclimate for now. We will eventually want to either customize/ignore these warnings, or fix them.

**Pull request merged**
